# This workflow uses a Python script to convert a text file to Markdown using the Gemini API.

name: Generate Markdown from Text

# Controls when the workflow is triggered.
on:
  push:
    paths:
      # The workflow will run only when changes are pushed to this specific file.
      - 'source.txt'

# Add permissions for the workflow to create a commit.
permissions:
  contents: write

# A workflow run is made up of one or more jobs.
jobs:
  convert_to_md:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Sets up Python on the runner.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installs the Python dependencies.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      # Runs the Python script to convert text to Markdown.
      - name: Run Markdown Converter Script
        run: python convert_to_md.py
        env:
          # Sets the GEMINI_API_KEY environment variable from a GitHub secret.
          # You must add this secret to your repository settings.
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # Commits the changes made to the Markdown file.
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto-generate README.md from source.txt'
          branch: main # Or the branch you are working on
